import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import { Toaster } from "@/components/ui/toaster";
import ChatEmbed from "@/components/admin/chatbots/share-chatbot/chat";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className=" bg-[#FFF] overflow-hidden"
    >
      <body className={poppins.className}>
        <Toaster />
        {children}
        <ChatEmbed id="d9e40b70-c0c1-4c23-aa06-ad8323a01482"></ChatEmbed>
      </body>
    </html>
  );
}
